bfs: bfs4.c
	gcc -o bfs bfs4.c

bfs-omp1: bfs-omp.c
	gcc -o bfs-omp1 bfs-omp.c -fopenmp

bfs-omp2: bfs-omp.c
	gcc -o bfs-omp2 bfs-omp2.c -fopenmp

bfs-omp3: bfs-omp3.c
	gcc -o bfs-omp3 bfs-omp3.c -fopenmp